import { SimplePool } from 'nostr-tools/pool';
import { finalizeEvent, getPublicKey, type UnsignedEvent } from 'nostr-tools/pure';
import createDebug from 'debug';

const debug = createDebug('signet:profile');

const PROFILE_RELAYS = [
    'wss://purplepag.es',
    'wss://relay.damus.io',
    'wss://relay.nostr.band',
    'wss://relay.primal.net',
    'wss://nos.lol',
];

export interface ProfileOverrides {
    display_name?: string;
    name?: string;
    about?: string;
    website?: string;
    picture?: string;
    image?: string;
    banner?: string;
    nip05?: string;
    lud16?: string;
}

function buildDefaultProfile(): ProfileOverrides {
    return {
        display_name: 'New Signet user',
        about: 'Autogenerated profile. Please customise it!',
        website: 'https://github.com/anthropics/signet',
        image: `https://robohash.org/${Math.random().toString(36).slice(2)}?set=set5`,
    };
}

/**
 * Create a skeleton profile for a new key.
 * Publishes kind 0 (profile), kind 3 (contacts), and kind 10002 (relay list).
 */
export async function createSkeletonProfile(
    secretKey: Uint8Array,
    relays: string[],
    profileOverrides?: Partial<ProfileOverrides>
): Promise<void> {
    const profile = {
        ...buildDefaultProfile(),
        ...profileOverrides,
    };

    const pubkey = getPublicKey(secretKey);
    const pool = new SimplePool();
    const targetRelays = relays.length > 0 ? relays : PROFILE_RELAYS;

    try {
        const createdAt = Math.floor(Date.now() / 1000);

        // Kind 0: Profile metadata
        const profileEvent = finalizeEvent({
            kind: 0,
            pubkey,
            content: JSON.stringify(profile),
            tags: [],
            created_at: createdAt,
        } as UnsignedEvent, secretKey);

        const profileResults = await Promise.allSettled(pool.publish(targetRelays, profileEvent));
        const profileSuccesses = profileResults.filter(r => r.status === 'fulfilled').length;
        debug('profile published to %d/%d relays', profileSuccesses, targetRelays.length);

        // Kind 3: Contact list (empty, just with a reference to signet author)
        const contactsEvent = finalizeEvent({
            kind: 3,
            pubkey,
            content: '',
            tags: [
                ['p', 'fa984bd7dbb282f07e16e7ae87b26a2a7b9b90b7246a44771f0cf5ae58018f52'],
                ['p', pubkey],
            ],
            created_at: createdAt,
        } as UnsignedEvent, secretKey);

        const contactsResults = await Promise.allSettled(pool.publish(targetRelays, contactsEvent));
        const contactsSuccesses = contactsResults.filter(r => r.status === 'fulfilled').length;
        debug('contacts published to %d/%d relays', contactsSuccesses, targetRelays.length);

        // Kind 10002: Relay list
        const relayListEvent = finalizeEvent({
            kind: 10002,
            pubkey,
            content: '',
            tags: PROFILE_RELAYS.map(relay => ['r', relay]),
            created_at: createdAt,
        } as UnsignedEvent, secretKey);

        const relayResults = await Promise.allSettled(pool.publish(targetRelays, relayListEvent));
        const relaySuccesses = relayResults.filter(r => r.status === 'fulfilled').length;
        debug('relay list published to %d/%d relays', relaySuccesses, targetRelays.length);

    } finally {
        pool.close(targetRelays);
    }
}
